# Configuration schema for automated extraction of Lie groupoid and Lie algebroid literature
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "polyidiot"  # Maintain repository ownership attribution
repo_name: "Arxiv-LieTheory"  # Modified repository name to reflect content domain
show_authors: True  # Enable author display for precise attribution
show_links: True  # Enable links to facilitate reference verification
show_badge: False
max_results: 100  # Expanded result count for comprehensive literature coverage
publish_readme: True
publish_gitpage: True
publish_wechat: False

# Output file path specifications
json_readme_path: './docs/LieTheory-arxiv-daily.json'
json_gitpage_path: './docs/LieTheory-arxiv-daily-web.json'
json_wechat_path: './docs/LieTheory-arxiv-daily-wechat.json'
md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# Domain-specific keywords with precise terminological filters
keywords:
    "Lie Groupoids and Lie Algebroids": 
        filters: [
            # Fundamental objects and structures
            "Lie groupoid", 
            "Lie algebroid",
            "Atiyah algebroid",
            "Courant algebroid",
            "VB-groupoid",
            "LA-groupoid",
            "symplectic groupoid",
            "Poisson groupoid",
            "contact groupoid",
            
            # Categorical and structural aspects
            "differentiable stack",
            "groupoid representation",
            "algebroid representation",
            "monoidal groupoid",
            "Morita equivalence",
            "groupoid cohomology",
            "algebroid cohomology",
            
            # Integration theory
            "integrability of Lie algebroids",
            "integration of Lie algebroids",
            "source-simply-connected",
            "local Lie groupoid",
            "A-path",
            
            # Connections to other mathematical structures
            "Poisson-Nijenhuis structure",
            "Dirac structure",
            "generalized complex structure",
            "multiplicative structure",
            "multiplicative vector field",
            "multiplicative differential form",
            
            # Higher structures
            "higher Lie groupoid", 
            "higher Lie algebroid",
            "Lie infinity-algebroid",
            "Lie 2-groupoid",
            "Lie 2-algebroid",
            "homotopy Poisson structure",
            
            # Related geometric structures
            "Jacobi manifold",
            "differentiable gerbe",
            "Atiyah sequence",
            "infinitesimal ideal system",
            
            # Applications and specialized topics
            "groupoid action",
            "Lie algebroid connection",
            "tangent Lie algebroid",
            "cotangent Lie algebroid",
            "momentum map",
            "reduction of Lie algebroids",
            "gauge theory on Lie groupoids",
            "deformation of Lie groupoids",
            "bialgebroid",
            "Hopf algebroid"
        ]
